"""remove confirm from video form

Revision ID: 4399c8d93e59
Revises: 5e2648362084
Create Date: 2017-05-22 22:14:45.512319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4399c8d93e59'
down_revision = '5e2648362084'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'confirm')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('confirm', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
