"""edit video table with user_id

Revision ID: fbb4a97fff80
Revises: ec62fb6b27e3
Create Date: 2017-05-21 19:57:11.303704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbb4a97fff80'
down_revision = 'ec62fb6b27e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('videos', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('videos', 'video',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('videos', 'video',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('videos', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
